base:
  retailrocket:
    events:
      filepath_or_buffer: '../datasets/retailrocket/events.csv'
      sep: ','
      skiprows: 1
      names: [ 'timestamp', 'userId', 'event', 'itemId', 'transactionId']

    events_filtered:
      filepath_or_buffer: '../datasets/retailrocket/events_filtered.csv'
      sep: ','
      skiprows: 1
      names: [ 'timestamp', 'userId', 'event', 'itemId', 'transactionId']

    category_tree:
      filepath_or_buffer: '../datasets/retailrocket/category_tree.csv'
      sep: ','
      skiprows: 1
      names: [ 'categoryid', 'parentid']

    item_properties_part1:
      filepath_or_buffer: '../datasets/retailrocket/item_properties_part1.csv'
      sep: ','
      skiprows: 1
      names: [ 'timestamp', 'itemId', 'property', 'value']

    item_properties_part2:
      filepath_or_buffer: '../datasets/retailrocket/item_properties_part2.csv'
      sep: ','
      skiprows: 1
      names: [ 'timestamp', 'itemId', 'property', 'value']

  testdata:
    filepath_or_buffer: '../datasets/fake_data.csv'
    sep: '\t'
    skiprows: 1
    names: [ 'userId', 'itemId', 'rating', 'timestamp']

  ml100k:
      filepath_or_buffer: '../datasets/ml-100k/u.data'
      sep: '\t'
      skiprows: 0
      names: [ 'userId', 'itemId', 'rating', 'timestamp']

  ml1m:
    filepath_or_buffer: '../datasets/ml-1m/ratings.dat'
    sep: '::'
    names: [ 'userId', 'itemId', 'rating', 'timestamp' ]

  model:
    gmf:
      learning_rate: 0.005
      weight_decay: 0.0000001
      latent_dim: 8
      epochs: 30
      num_negative: 10
      batch_size: 1024
      cuda: False
      optimizer_name: 'adam'
    mlp:
      learning_rate: 0.005
      weight_decay: 0.0000001
      latent_dim: 8
      epochs: 30
      num_negative: 10
      batch_size: 1024
      cuda: False
      optimizer_name: 'adam'
    als:
      learning_rate: 0.1
      latent_dim: 100
      epochs: 10
      reg_term: 0.001
    bpr:
      learning_rate: 0.01
      latent_dim: 100
      epochs: 10
      reg_term: 0.0
    emf:
      learning_rate: 0.01
      reg_term: 0.001
      expl_reg_term: 0.0
      latent_dim: 80
      epochs: 10
      positive_threshold: 3
      knn: 10
    mf:
      learning_rate: 0.01
      reg_term: 0.001
      expl_reg_term: 0.0
      latent_dim: 80
      epochs: 10
      positive_threshold: 3
      knn: 10
    autoencoder:
      learning_rate: 0.005
      weight_decay: 0.0000001
      hidden_layer_features: 8
      epochs: 30
      cuda: False
      optimizer_name: 'adam'
      positive_threshold: 3
      knn: 10
      expl: true


